package com.inossem.wms.wsdl.sap.getdo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.inossem.wms.util.UtilProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_CW_WMS_GET_DO_S_OUTService", targetNamespace = "urn:sinopec:ecc:iwms:cw", wsdlLocation = "http://127.0.0.1:8080/wms/web/interface/getdo.wsdl")
public class SICWWMSGETDOSOUTService
    extends Service
{

    private final static URL SICWWMSGETDOSOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICWWMSGETDOSOUTSERVICE_EXCEPTION;
    private final static QName SICWWMSGETDOSOUTSERVICE_QNAME = new QName("urn:sinopec:ecc:iwms:cw", "SI_CW_WMS_GET_DO_S_OUTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UtilProperties.getInstance().getWmsUrl() + "/wms/web/interface/getdo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SICWWMSGETDOSOUTSERVICE_WSDL_LOCATION = url;
        SICWWMSGETDOSOUTSERVICE_EXCEPTION = e;
    }

    public SICWWMSGETDOSOUTService() {
        super(__getWsdlLocation(), SICWWMSGETDOSOUTSERVICE_QNAME);
    }

    public SICWWMSGETDOSOUTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICWWMSGETDOSOUTSERVICE_QNAME, features);
    }

    public SICWWMSGETDOSOUTService(URL wsdlLocation) {
        super(wsdlLocation, SICWWMSGETDOSOUTSERVICE_QNAME);
    }

    public SICWWMSGETDOSOUTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICWWMSGETDOSOUTSERVICE_QNAME, features);
    }

    public SICWWMSGETDOSOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICWWMSGETDOSOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSGETDOSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSGETDOSOUT getHTTPPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSGETDOSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSGETDOSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSGETDOSOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSGETDOSOUT.class, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSGETDOSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSGETDOSOUT getHTTPSPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSGETDOSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSGETDOSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSGETDOSOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSGETDOSOUT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICWWMSGETDOSOUTSERVICE_EXCEPTION!= null) {
            throw SICWWMSGETDOSOUTSERVICE_EXCEPTION;
        }
        return SICWWMSGETDOSOUTSERVICE_WSDL_LOCATION;
    }

}
