
package com.inossem.wms.wsdl.mes.update;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WmSvcInterOpeSoap", targetNamespace = "http://www.mes30.com/wm_webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WmSvcInterOpeSoap {


    /**
     * 
     * @param passwd
     * @param opeTypeCode
     * @param dtoSet
     * @param shiftBeginTime
     * @param shiftEndTime
     * @param userId
     * @param credentialCode
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.WmIopRetVal
     */
    @WebMethod(operationName = "CreateOpeBill", action = "http://www.mes30.com/wm_webservices/CreateOpeBill")
    @WebResult(name = "CreateOpeBillResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "CreateOpeBill", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CreateOpeBill")
    @ResponseWrapper(localName = "CreateOpeBillResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CreateOpeBillResponse")
    public WmIopRetVal createOpeBill(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "passwd", targetNamespace = "http://www.mes30.com/wm_webservices")
        String passwd,
        @WebParam(name = "credentialCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String credentialCode,
        @WebParam(name = "opeTypeCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String opeTypeCode,
        @WebParam(name = "shiftBeginTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar shiftBeginTime,
        @WebParam(name = "shiftEndTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar shiftEndTime,
        @WebParam(name = "dtoSet", targetNamespace = "http://www.mes30.com/wm_webservices")
        ArrayOfWmMvRecInteropeDto dtoSet);

    /**
     * 
     * @param passwd
     * @param opeTypeCode
     * @param dtoSet
     * @param shiftBeginTime
     * @param shiftEndTime
     * @param userId
     * @param credentialCode
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.WmIopRetVal
     */
    @WebMethod(operationName = "CreateOpeBillAndBook", action = "http://www.mes30.com/wm_webservices/CreateOpeBillAndBook")
    @WebResult(name = "CreateOpeBillAndBookResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "CreateOpeBillAndBook", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CreateOpeBillAndBook")
    @ResponseWrapper(localName = "CreateOpeBillAndBookResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CreateOpeBillAndBookResponse")
    public WmIopRetVal createOpeBillAndBook(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "passwd", targetNamespace = "http://www.mes30.com/wm_webservices")
        String passwd,
        @WebParam(name = "credentialCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String credentialCode,
        @WebParam(name = "opeTypeCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String opeTypeCode,
        @WebParam(name = "shiftBeginTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar shiftBeginTime,
        @WebParam(name = "shiftEndTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar shiftEndTime,
        @WebParam(name = "dtoSet", targetNamespace = "http://www.mes30.com/wm_webservices")
        ArrayOfWmMvRecInteropeDto dtoSet);

    /**
     * 
     * @param passwd
     * @param opeBillCode
     * @param userId
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.WmIopRetVal
     */
    @WebMethod(operationName = "Book", action = "http://www.mes30.com/wm_webservices/Book")
    @WebResult(name = "BookResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "Book", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.Book")
    @ResponseWrapper(localName = "BookResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.BookResponse")
    public WmIopRetVal book(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "passwd", targetNamespace = "http://www.mes30.com/wm_webservices")
        String passwd,
        @WebParam(name = "opeBillCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String opeBillCode);

    /**
     * 
     * @param passwd
     * @param opeBillCode
     * @param userId
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.WmIopRetVal
     */
    @WebMethod(operationName = "DeleteOpeBill", action = "http://www.mes30.com/wm_webservices/DeleteOpeBill")
    @WebResult(name = "DeleteOpeBillResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "DeleteOpeBill", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DeleteOpeBill")
    @ResponseWrapper(localName = "DeleteOpeBillResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DeleteOpeBillResponse")
    public WmIopRetVal deleteOpeBill(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "passwd", targetNamespace = "http://www.mes30.com/wm_webservices")
        String passwd,
        @WebParam(name = "opeBillCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String opeBillCode);

    /**
     * 
     * @param passwd
     * @param userId
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetEarliestOprBeginTime", action = "http://www.mes30.com/wm_webservices/GetEarliestOprBeginTime")
    @WebResult(name = "GetEarliestOprBeginTimeResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "GetEarliestOprBeginTime", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.GetEarliestOprBeginTime")
    @ResponseWrapper(localName = "GetEarliestOprBeginTimeResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.GetEarliestOprBeginTimeResponse")
    public XMLGregorianCalendar getEarliestOprBeginTime(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "passwd", targetNamespace = "http://www.mes30.com/wm_webservices")
        String passwd);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "WgtValPrecision", action = "http://www.mes30.com/wm_webservices/WgtValPrecision")
    @WebResult(name = "WgtValPrecisionResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "WgtValPrecision", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.WgtValPrecision")
    @ResponseWrapper(localName = "WgtValPrecisionResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.WgtValPrecisionResponse")
    public int wgtValPrecision();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Version", action = "http://www.mes30.com/wm_webservices/Version")
    @WebResult(name = "VersionResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "Version", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.Version")
    @ResponseWrapper(localName = "VersionResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.VersionResponse")
    public String version();

    /**
     * 
     * @param mtrlcode
     * @param userId
     * @param querytime
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.ArrayOfWmInvQueryResult
     */
    @WebMethod(operationName = "GetCurrentStockInfos", action = "http://www.mes30.com/wm_webservices/GetCurrentStockInfos")
    @WebResult(name = "GetCurrentStockInfosResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "GetCurrentStockInfos", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.GetCurrentStockInfos")
    @ResponseWrapper(localName = "GetCurrentStockInfosResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.GetCurrentStockInfosResponse")
    public ArrayOfWmInvQueryResult getCurrentStockInfos(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "mtrlcode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String mtrlcode,
        @WebParam(name = "querytime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar querytime);

    /**
     * 
     * @param mtrlcode
     * @param locationId
     * @param userId
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.ArrayOfWmInvQueryNewResult
     */
    @WebMethod(operationName = "GetCurrentStockInfosByMtrlOrlocalId", action = "http://www.mes30.com/wm_webservices/GetCurrentStockInfosByMtrlOrlocalId")
    @WebResult(name = "GetCurrentStockInfosByMtrlOrlocalIdResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "GetCurrentStockInfosByMtrlOrlocalId", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.GetCurrentStockInfosByMtrlOrlocalId")
    @ResponseWrapper(localName = "GetCurrentStockInfosByMtrlOrlocalIdResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.GetCurrentStockInfosByMtrlOrlocalIdResponse")
    public ArrayOfWmInvQueryNewResult getCurrentStockInfosByMtrlOrlocalId(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "mtrlcode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String mtrlcode,
        @WebParam(name = "LocationId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String locationId);

    /**
     * 
     * @param userId
     * @param cancelBillId
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.ArrayOfString
     */
    @WebMethod(operationName = "CancelBookedBill", action = "http://www.mes30.com/wm_webservices/CancelBookedBill")
    @WebResult(name = "CancelBookedBillResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "CancelBookedBill", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CancelBookedBill")
    @ResponseWrapper(localName = "CancelBookedBillResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CancelBookedBillResponse")
    public ArrayOfString cancelBookedBill(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "cancelBillId", targetNamespace = "http://www.mes30.com/wm_webservices")
        int cancelBillId);

    /**
     * 
     * @param cancelBillCode
     * @param userId
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.ArrayOfString
     */
    @WebMethod(operationName = "CancelBookedBillByBillCode", action = "http://www.mes30.com/wm_webservices/CancelBookedBillByBillCode")
    @WebResult(name = "CancelBookedBillByBillCodeResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "CancelBookedBillByBillCode", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CancelBookedBillByBillCode")
    @ResponseWrapper(localName = "CancelBookedBillByBillCodeResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.CancelBookedBillByBillCodeResponse")
    public ArrayOfString cancelBookedBillByBillCode(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "cancelBillCode", targetNamespace = "http://www.mes30.com/wm_webservices")
        String cancelBillCode);

    /**
     * 
     * @param chkShiftId
     * @param chkItems
     * @param userId
     * @param ipAddr
     * @param chkTime
     * @return
     *     returns com.inossem.wms.wsdl.mes.update.ArrayOfString
     */
    @WebMethod(operationName = "PhysicalCheck", action = "http://www.mes30.com/wm_webservices/PhysicalCheck")
    @WebResult(name = "PhysicalCheckResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "PhysicalCheck", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.PhysicalCheck")
    @ResponseWrapper(localName = "PhysicalCheckResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.PhysicalCheckResponse")
    public ArrayOfString physicalCheck(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "chkTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar chkTime,
        @WebParam(name = "chkShiftId", targetNamespace = "http://www.mes30.com/wm_webservices")
        int chkShiftId,
        @WebParam(name = "ipAddr", targetNamespace = "http://www.mes30.com/wm_webservices")
        String ipAddr,
        @WebParam(name = "chkItems", targetNamespace = "http://www.mes30.com/wm_webservices")
        ArrayOfWmPhChkItem chkItems);

    /**
     * 
     * @param userId
     * @param chkTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PhysicalCheckCancel", action = "http://www.mes30.com/wm_webservices/PhysicalCheckCancel")
    @WebResult(name = "PhysicalCheckCancelResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "PhysicalCheckCancel", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.PhysicalCheckCancel")
    @ResponseWrapper(localName = "PhysicalCheckCancelResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.PhysicalCheckCancelResponse")
    public String physicalCheckCancel(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "chkTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar chkTime);

    /**
     * 
     * @param sumTime
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DailySum", action = "http://www.mes30.com/wm_webservices/DailySum")
    @WebResult(name = "DailySumResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "DailySum", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DailySum")
    @ResponseWrapper(localName = "DailySumResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DailySumResponse")
    public String dailySum(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "sumTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar sumTime);

    /**
     * 
     * @param cancelTime
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DailySumCancel", action = "http://www.mes30.com/wm_webservices/DailySumCancel")
    @WebResult(name = "DailySumCancelResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "DailySumCancel", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DailySumCancel")
    @ResponseWrapper(localName = "DailySumCancelResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DailySumCancelResponse")
    public String dailySumCancel(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "cancelTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar cancelTime);

    /**
     * 
     * @param submitTime
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DailySumSubmit", action = "http://www.mes30.com/wm_webservices/DailySumSubmit")
    @WebResult(name = "DailySumSubmitResult", targetNamespace = "http://www.mes30.com/wm_webservices")
    @RequestWrapper(localName = "DailySumSubmit", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DailySumSubmit")
    @ResponseWrapper(localName = "DailySumSubmitResponse", targetNamespace = "http://www.mes30.com/wm_webservices", className = "com.inossem.wms.wsdl.mes.update.DailySumSubmitResponse")
    public String dailySumSubmit(
        @WebParam(name = "userId", targetNamespace = "http://www.mes30.com/wm_webservices")
        String userId,
        @WebParam(name = "submitTime", targetNamespace = "http://www.mes30.com/wm_webservices")
        XMLGregorianCalendar submitTime);

}
