
package com.inossem.wms.wsdl.sap.outputc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.inossem.wms.util.UtilProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_CW_WMS_DO_REVERSE_S_OUTService", targetNamespace = "urn:sinopec:ecc:iwms:cw", wsdlLocation = "http://10.5.91.139:50000/dir/wsdl?p=sa/ca6e49cb34bc3343920e587910328e37")
public class SICWWMSDOREVERSESOUTService
    extends Service
{

    private final static URL SICWWMSDOREVERSESOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICWWMSDOREVERSESOUTSERVICE_EXCEPTION;
    private final static QName SICWWMSDOREVERSESOUTSERVICE_QNAME = new QName("urn:sinopec:ecc:iwms:cw", "SI_CW_WMS_DO_REVERSE_S_OUTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UtilProperties.getInstance().getWmsUrl() + "/wms/web/interface/outputc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SICWWMSDOREVERSESOUTSERVICE_WSDL_LOCATION = url;
        SICWWMSDOREVERSESOUTSERVICE_EXCEPTION = e;
    }

    public SICWWMSDOREVERSESOUTService() {
        super(__getWsdlLocation(), SICWWMSDOREVERSESOUTSERVICE_QNAME);
    }

    public SICWWMSDOREVERSESOUTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICWWMSDOREVERSESOUTSERVICE_QNAME, features);
    }

    public SICWWMSDOREVERSESOUTService(URL wsdlLocation) {
        super(wsdlLocation, SICWWMSDOREVERSESOUTSERVICE_QNAME);
    }

    public SICWWMSDOREVERSESOUTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICWWMSDOREVERSESOUTSERVICE_QNAME, features);
    }

    public SICWWMSDOREVERSESOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICWWMSDOREVERSESOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSDOREVERSESOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSDOREVERSESOUT getHTTPPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSDOREVERSESOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSDOREVERSESOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSDOREVERSESOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSDOREVERSESOUT.class, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSDOREVERSESOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSDOREVERSESOUT getHTTPSPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSDOREVERSESOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSDOREVERSESOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSDOREVERSESOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSDOREVERSESOUT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICWWMSDOREVERSESOUTSERVICE_EXCEPTION!= null) {
            throw SICWWMSDOREVERSESOUTSERVICE_EXCEPTION;
        }
        return SICWWMSDOREVERSESOUTSERVICE_WSDL_LOCATION;
    }

}
