
package com.inossem.wms.wsdl.sap.inputc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.inossem.wms.util.UtilProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_CW_WMS_CANCEL_MATDOC_S_OUTService", targetNamespace = "urn:sinopec:ecc:iwms:cw", wsdlLocation = "http://10.5.91.139:50000/dir/wsdl?p=sa/ca0d922b8c373a7c8757aef75622c5aa")
public class SICWWMSCANCELMATDOCSOUTService
    extends Service
{

    private final static URL SICWWMSCANCELMATDOCSOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICWWMSCANCELMATDOCSOUTSERVICE_EXCEPTION;
    private final static QName SICWWMSCANCELMATDOCSOUTSERVICE_QNAME = new QName("urn:sinopec:ecc:iwms:cw", "SI_CW_WMS_CANCEL_MATDOC_S_OUTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UtilProperties.getInstance().getWmsUrl() + "/wms/web/interface/inputc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SICWWMSCANCELMATDOCSOUTSERVICE_WSDL_LOCATION = url;
        SICWWMSCANCELMATDOCSOUTSERVICE_EXCEPTION = e;
    }

    public SICWWMSCANCELMATDOCSOUTService() {
        super(__getWsdlLocation(), SICWWMSCANCELMATDOCSOUTSERVICE_QNAME);
    }

    public SICWWMSCANCELMATDOCSOUTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICWWMSCANCELMATDOCSOUTSERVICE_QNAME, features);
    }

    public SICWWMSCANCELMATDOCSOUTService(URL wsdlLocation) {
        super(wsdlLocation, SICWWMSCANCELMATDOCSOUTSERVICE_QNAME);
    }

    public SICWWMSCANCELMATDOCSOUTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICWWMSCANCELMATDOCSOUTSERVICE_QNAME, features);
    }

    public SICWWMSCANCELMATDOCSOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICWWMSCANCELMATDOCSOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSCANCELMATDOCSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSCANCELMATDOCSOUT getHTTPPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSCANCELMATDOCSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSCANCELMATDOCSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSCANCELMATDOCSOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSCANCELMATDOCSOUT.class, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSCANCELMATDOCSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSCANCELMATDOCSOUT getHTTPSPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSCANCELMATDOCSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSCANCELMATDOCSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSCANCELMATDOCSOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSCANCELMATDOCSOUT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICWWMSCANCELMATDOCSOUTSERVICE_EXCEPTION!= null) {
            throw SICWWMSCANCELMATDOCSOUTSERVICE_EXCEPTION;
        }
        return SICWWMSCANCELMATDOCSOUTSERVICE_WSDL_LOCATION;
    }

}
