
package com.inossem.wms.wsdl.sap.output;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_CW_WMS_DO_POST_S_OUT", targetNamespace = "urn:sinopec:ecc:iwms:cw")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SICWWMSDOPOSTSOUT {


    /**
     * 
     * @param mtCWWMSDOPOSTREQ
     * @return
     *     returns com.inossem.wms.wsdl.sap.output.DTCWWMSDOPOSTRESP
     */
    @WebMethod(operationName = "SI_CW_WMS_DO_POST_S_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_CW_WMS_DO_POST_RESP", targetNamespace = "urn:sinopec:ecc:iwms:cw", partName = "MT_CW_WMS_DO_POST_RESP")
    public DTCWWMSDOPOSTRESP siCWWMSDOPOSTSOUT(
        @WebParam(name = "MT_CW_WMS_DO_POST_REQ", targetNamespace = "urn:sinopec:ecc:iwms:cw", partName = "MT_CW_WMS_DO_POST_REQ")
        DTCWWMSDOPOSTREQ mtCWWMSDOPOSTREQ);

}
