
package com.inossem.wms.wsdl.sap.input;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.inossem.wms.util.UtilProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_CW_WMS_MATDOC_POST_S_OUTService", targetNamespace = "urn:sinopec:ecc:iwms:cw", wsdlLocation = "http://10.5.91.139:50000/dir/wsdl?p=sa/78d1adfe97b331629a9b68fb8ad44815")
public class SICWWMSMATDOCPOSTSOUTService
    extends Service
{

    private final static URL SICWWMSMATDOCPOSTSOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICWWMSMATDOCPOSTSOUTSERVICE_EXCEPTION;
    private final static QName SICWWMSMATDOCPOSTSOUTSERVICE_QNAME = new QName("urn:sinopec:ecc:iwms:cw", "SI_CW_WMS_MATDOC_POST_S_OUTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UtilProperties.getInstance().getWmsUrl() + "/wms/web/interface/input.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SICWWMSMATDOCPOSTSOUTSERVICE_WSDL_LOCATION = url;
        SICWWMSMATDOCPOSTSOUTSERVICE_EXCEPTION = e;
    }

    public SICWWMSMATDOCPOSTSOUTService() {
        super(__getWsdlLocation(), SICWWMSMATDOCPOSTSOUTSERVICE_QNAME);
    }

    public SICWWMSMATDOCPOSTSOUTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICWWMSMATDOCPOSTSOUTSERVICE_QNAME, features);
    }

    public SICWWMSMATDOCPOSTSOUTService(URL wsdlLocation) {
        super(wsdlLocation, SICWWMSMATDOCPOSTSOUTSERVICE_QNAME);
    }

    public SICWWMSMATDOCPOSTSOUTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICWWMSMATDOCPOSTSOUTSERVICE_QNAME, features);
    }

    public SICWWMSMATDOCPOSTSOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICWWMSMATDOCPOSTSOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSMATDOCPOSTSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSMATDOCPOSTSOUT getHTTPPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSMATDOCPOSTSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSMATDOCPOSTSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICWWMSMATDOCPOSTSOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTP_Port"), SICWWMSMATDOCPOSTSOUT.class, features);
    }

    /**
     * 
     * @return
     *     returns SICWWMSMATDOCPOSTSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSMATDOCPOSTSOUT getHTTPSPort() {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSMATDOCPOSTSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICWWMSMATDOCPOSTSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICWWMSMATDOCPOSTSOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sinopec:ecc:iwms:cw", "HTTPS_Port"), SICWWMSMATDOCPOSTSOUT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICWWMSMATDOCPOSTSOUTSERVICE_EXCEPTION!= null) {
            throw SICWWMSMATDOCPOSTSOUTSERVICE_EXCEPTION;
        }
        return SICWWMSMATDOCPOSTSOUTSERVICE_WSDL_LOCATION;
    }

}
