
package com.inossem.wms.wsdl.sap.input;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_CW_WMS_MATDOC_POST_S_OUT", targetNamespace = "urn:sinopec:ecc:iwms:cw")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SICWWMSMATDOCPOSTSOUT {


    /**
     * 
     * @param mtCWWMSMATDOCPOSTREQ
     * @return
     *     returns com.inossem.wms.wsdl.sap.input.DTCWWMSMATDOCPOSTRESP
     */
    @WebMethod(operationName = "SI_CW_WMS_MATDOC_POST_S_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_CW_WMS_MATDOC_POST_RESP", targetNamespace = "urn:sinopec:ecc:iwms:cw", partName = "MT_CW_WMS_MATDOC_POST_RESP")
    public DTCWWMSMATDOCPOSTRESP siCWWMSMATDOCPOSTSOUT(
        @WebParam(name = "MT_CW_WMS_MATDOC_POST_REQ", targetNamespace = "urn:sinopec:ecc:iwms:cw", partName = "MT_CW_WMS_MATDOC_POST_REQ")
        DTCWWMSMATDOCPOSTREQ mtCWWMSMATDOCPOSTREQ);

}
