
package com.inossem.wms.wsdl.lims.report;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 参数：开始时间，结束时间，装置ID，采样点ID，样品名称,样品编号，批次，规格；除了样品编号和批次，其余参数如规格，还必须定义时间
     * 
     * @param batchName
     * @param sDate
     * @param specification
     * @param eDate
     * @param spId
     * @param locId
     * @param sampName
     * @param sId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PRO_LIMS_QUERYCOM", action = "http://tempuri.org/PRO_LIMS_QUERYCOM")
    @WebResult(name = "PRO_LIMS_QUERYCOMResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PRO_LIMS_QUERYCOM", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.PROLIMSQUERYCOM")
    @ResponseWrapper(localName = "PRO_LIMS_QUERYCOMResponse", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.PROLIMSQUERYCOMResponse")
    public String proLIMSQUERYCOM(
        @WebParam(name = "s_date", targetNamespace = "http://tempuri.org/")
        String sDate,
        @WebParam(name = "e_date", targetNamespace = "http://tempuri.org/")
        String eDate,
        @WebParam(name = "loc_id", targetNamespace = "http://tempuri.org/")
        String locId,
        @WebParam(name = "sp_id", targetNamespace = "http://tempuri.org/")
        String spId,
        @WebParam(name = "samp_name", targetNamespace = "http://tempuri.org/")
        String sampName,
        @WebParam(name = "s_id", targetNamespace = "http://tempuri.org/")
        String sId,
        @WebParam(name = "batch_name", targetNamespace = "http://tempuri.org/")
        String batchName,
        @WebParam(name = "specification", targetNamespace = "http://tempuri.org/")
        String specification);

    /**
     * 按批次号取数。参数：批号；参数不能为空
     * 
     * @param batchName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LIMS_QADATA_BATCH", action = "http://tempuri.org/LIMS_QADATA_BATCH")
    @WebResult(name = "LIMS_QADATA_BATCHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LIMS_QADATA_BATCH", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATABATCH")
    @ResponseWrapper(localName = "LIMS_QADATA_BATCHResponse", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATABATCHResponse")
    public String limsQADATABATCH(
        @WebParam(name = "batch_name", targetNamespace = "http://tempuri.org/")
        String batchName);

    /**
     * 按样品编号取数。参数：样品编号；参数不能为空
     * 
     * @param sampleId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LIMS_QADATA_ID", action = "http://tempuri.org/LIMS_QADATA_ID")
    @WebResult(name = "LIMS_QADATA_IDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LIMS_QADATA_ID", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATAID")
    @ResponseWrapper(localName = "LIMS_QADATA_IDResponse", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATAIDResponse")
    public String limsQADATAID(
        @WebParam(name = "sample_id", targetNamespace = "http://tempuri.org/")
        String sampleId);

    /**
     * 按规格取数。参数：采样开始时间，结束时间，规格；三个参数都不能为空
     * 
     * @param sDate
     * @param guige
     * @param eDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LIMS_QADATA_GUIGE", action = "http://tempuri.org/LIMS_QADATA_GUIGE")
    @WebResult(name = "LIMS_QADATA_GUIGEResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LIMS_QADATA_GUIGE", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATAGUIGE")
    @ResponseWrapper(localName = "LIMS_QADATA_GUIGEResponse", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATAGUIGEResponse")
    public String limsQADATAGUIGE(
        @WebParam(name = "s_date", targetNamespace = "http://tempuri.org/")
        String sDate,
        @WebParam(name = "e_date", targetNamespace = "http://tempuri.org/")
        String eDate,
        @WebParam(name = "guige", targetNamespace = "http://tempuri.org/")
        String guige);

    /**
     * 参数：样品名称,批次，规格；
     * 
     * @param batchName
     * @param specification
     * @param sampName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LIMS_QADATA_3", action = "http://tempuri.org/LIMS_QADATA_3")
    @WebResult(name = "LIMS_QADATA_3Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LIMS_QADATA_3", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATA3")
    @ResponseWrapper(localName = "LIMS_QADATA_3Response", targetNamespace = "http://tempuri.org/", className = "com.inossem.wms.wsdl.lims.report.LIMSQADATA3Response")
    public String limsQADATA3(
        @WebParam(name = "samp_name", targetNamespace = "http://tempuri.org/")
        String sampName,
        @WebParam(name = "batch_name", targetNamespace = "http://tempuri.org/")
        String batchName,
        @WebParam(name = "specification", targetNamespace = "http://tempuri.org/")
        String specification);

}
